Models/Event.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Collections.Generic;

namespace TournamentsWebApplication.Models
{
    public class Event
    {
        [Key]

        public int EventID { get; set; }
        public int TournamentID { get; set; }
        public virtual Tournament FK_TournamentID { get; set; }

        [Display(Name = "Event Name")]
        public string EventName { get; set; }

        [Display(Name = "Event Number")]
        public int EventNumber { get; set; }

        [Display(Name = "Event Date Time")]
        public DateTime? EventDateTime { get; set; }

        [Display(Name = "Event End Date Time")]
        public DateTime? EventEndDateTime { get; set; }

        [Display(Name = "Auto Close")]
        public bool AutoClose { get; set; }
        public virtual ICollection<EventDetail> EventDetail { get; set; }


    }

}

Controllers/EventDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TournamentsWebApplication.Data;
using TournamentsWebApplication.Models;
using TournamentsWebApplication.ViewModels;

namespace TournamentsWebApplication.Controllers
{
    public class EventDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventDetailsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EventDetails
        public async Task<IActionResult> Index(int id)
        {

            EventEventdetailsViewModel edcViewModel = new EventEventdetailsViewModel()
            {

                Event = (Event)_context.Event.Find(id),
                EventDetail = _context.EventDetail.ToList().Where(e => e.EventID == id).OrderBy(e => e.EventDetailID),
                FirstTimer = false
            

            };
            //var applicationDbContext = _context.EventDetail.Include(e => e.FK_EventDetailStatusID).Include(e => e.FK_EventID);



            //ViewData["EventDetailStatusID"] = new SelectList(_context.Set<EventDetailStatus>(), "EventDetailStatusID", "EventDetailStatusName");
            return View(edcViewModel);
        }

        // GET: EventDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventDetail = await _context.EventDetail
                .Include(e => e.FK_EventDetailStatusID)
                .Include(e => e.FK_EventID)
                .FirstOrDefaultAsync(m => m.EventDetailID == id);
            if (eventDetail == null)
            {
                return NotFound();
            }
            ViewData["EventDetailStatusID"] = new SelectList(_context.Set<EventDetailStatus>(), "EventDetailStatusID", "EventDetailStatusName", eventDetail.EventDetailStatusID);
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID", eventDetail.EventID);
            return View(eventDetail);
        }

        // GET: EventDetails/Create
        public IActionResult Create()
        {

            //EventEventDetailStatusViewModel edcViewModel = new EventDetailCreateViewModel()
            //{
            //    Event = repositorywrapper.Event.GetById(id),
            //    EventDetailStatus = repositorywrapper.EventDetailStatus.FindAll().ToList()

            //};

            //ViewBag.Title = "Create Event Detail";
            //ViewBag.StatusList = new SelectList(repositorywrapper.EventDetailStatus.FindAll().ToList(), "EventDetailStatusID", "EventDetailStatusName");


            //return View(edcViewModel);



            ViewData["EventDetailStatusID"] = new SelectList(_context.Set<EventDetailStatus>(), "EventDetailStatusID", "EventDetailStatusName");
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID");
            return View();
        }

        // POST: EventDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventDetailID,EventID,EventDetailStatusID,EventDetailName,EventDetailNumber,EventDetailOdd,FinishingPosition,FirstTimer")] EventDetail eventDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            //ViewData["EventDetailStatusID"] = new SelectList(_context.Set<EventDetailStatus>(), "EventDetailStatusID", "EventDetailStatusName", eventDetail.FK_EventDetailStatusID);
            //ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID", eventDetail.EventID);
            return View(eventDetail);
        }

        // GET: EventDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventDetail = await _context.EventDetail.FindAsync(id);
            if (eventDetail == null)
            {
                return NotFound();
            }
            ViewData["EventDetailStatusID"] = new SelectList(_context.Set<EventDetailStatus>(), "EventDetailStatusID", "EventDetailStatusName", eventDetail.EventDetailStatusID);
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID", eventDetail.EventID);
            return View(eventDetail);
        }

        // POST: EventDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventDetailID,EventID,EventDetailStatusID,EventDetailName,EventDetailNumber,EventDetailOdd,FinishingPosition,FirstTimer")] EventDetail eventDetail)
        {
            if (id != eventDetail.EventDetailID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventDetailExists(eventDetail.EventDetailID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EventDetailStatusID"] = new SelectList(_context.Set<EventDetailStatus>(), "EventDetailStatusID", "EventDetailStatusID", eventDetail.EventDetailStatusID);
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID", eventDetail.EventID);
            return View(eventDetail);
        }

        // GET: EventDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventDetail = await _context.EventDetail
                .Include(e => e.FK_EventDetailStatusID)
                .Include(e => e.FK_EventID)
                .FirstOrDefaultAsync(m => m.EventDetailID == id);
            if (eventDetail == null)
            {
                return NotFound();
            }

            ViewData["EventDetailStatusID"] = new SelectList(_context.Set<EventDetailStatus>(), "EventDetailStatusID", "EventDetailStatusName", eventDetail.EventDetailStatusID);
            ViewData["EventID"] = new SelectList(_context.Event, "EventID", "EventID", eventDetail.EventID);
            return View(eventDetail);
        }

        // POST: EventDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventDetail = await _context.EventDetail.FindAsync(id);
            _context.EventDetail.Remove(eventDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool EventDetailExists(int id)
        {
            return _context.EventDetail.Any(e => e.EventDetailID == id);
        }
    }
}

Controllers/EventsController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TournamentsWebApplication.Data;
using TournamentsWebApplication.Models;
using TournamentsWebApplication.ViewModels;

namespace TournamentsWebApplication.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventsController(ApplicationDbContext context)
        {
            _context = context;  
        }

       // [AllowAnonymous]
        // GET: Events
        public async Task<IActionResult> Index(int id)
        {


            EventTourViewModel eventTourViewModel = new EventTourViewModel()
            {
                Tournament = (Tournament)_context.Tournament.Find(id),
                Event = _context.Event.ToList().Where(e => e.TournamentID == id).OrderBy(e => e.EventID),
                AutoClose = false

            };


            return View(eventTourViewModel);

            //string redirectUrl = Url.Action("Refresh");
            //return Json(new { redirectUrl });
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .Include(e => e.FK_TournamentID)
                .FirstOrDefaultAsync(m => m.EventID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        private object FK_TournamentID(Event arg)
        {
            throw new NotImplementedException();
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            ViewData["TournamentID"] = new SelectList(_context.Tournament, "TournamentID", "TournamentID");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventID,TournamentID,EventName,EventNumber,EventDateTime,EventEndDateTime,AutoClose")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            ViewData["TournamentID"] = new SelectList(_context.Tournament, "TournamentID", "TournamentID", @event.TournamentID);
            return View(@event);
        }
       

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["TournamentID"] = new SelectList(_context.Tournament, "TournamentID", "TournamentID", @event.TournamentID);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventID,TournamentID,EventName,EventNumber,EventDateTime,EventEndDateTime,AutoClose")] Event @event)
        {
            if (id != @event.EventID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TournamentID"] = new SelectList(_context.Tournament, "TournamentID", "TournamentID", @event.TournamentID);
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
               .Include(e => e.FK_TournamentID)
                .FirstOrDefaultAsync(m => m.EventID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Event.FindAsync(id);
            _context.Event.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.EventID == id);
        }
    }
}

Views/Events/Create.cshtml
@model TournamentsWebApplication.Models.Event

@{
    ViewData["Title"] = "Create";
}


<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*@Html.HiddenFor(model => model.FK_TournamentID)*@
            @*@Html.HiddenFor(model => model.TournamentID)*@
            <div class="form-group">
                <label asp-for="TournamentID" class="control-label"></label>
                <select asp-for="TournamentID" class="form-control" asp-items="ViewBag.TournamentID"></select>
            </div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventNumber" class="control-label"></label>
                <input asp-for="EventNumber" class="form-control" />
                <span asp-validation-for="EventNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDateTime" class="control-label"></label>
                <input asp-for="EventDateTime" class="form-control" />
                <span asp-validation-for="EventDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventEndDateTime" class="control-label"></label>
                <input asp-for="EventEndDateTime" class="form-control" />
                <span asp-validation-for="EventEndDateTime" class="text-danger"></span>
            </div>

            @*Add Checkbox or Dropdown*@
            <div class="form-check">
                <label asp-for="AutoClose" class="control-label"></label>
                <input class="form-check-input" type="checkbox" asp-for="AutoClose" style="margin:5px; width: 15px; height: 13px; overflow: hidden;"/>
                <span asp-validation-for="AutoClose" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form> 
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Events/Delete.cshtml
@model TournamentsWebApplication.Models.Event

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FK_TournamentID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FK_TournamentID.TournamentID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventEndDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventEndDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AutoClose)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AutoClose)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Events/Details.cshtml
@model TournamentsWebApplication.Models.Event

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FK_TournamentID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FK_TournamentID.TournamentID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventEndDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventEndDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AutoClose)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AutoClose)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EventID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Events/Edit.cshtml
@model TournamentsWebApplication.Models.Event

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventID" />
            <div class="form-group">
                <label asp-for="TournamentID" class="control-label"></label>
                <select asp-for="TournamentID" class="form-control" asp-items="ViewBag.TournamentID"></select>
                <span asp-validation-for="TournamentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventNumber" class="control-label"></label>
                <input asp-for="EventNumber" class="form-control" />
                <span asp-validation-for="EventNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDateTime" class="control-label"></label>
                <input asp-for="EventDateTime" class="form-control" />
                <span asp-validation-for="EventDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventEndDateTime" class="control-label"></label>
                <input asp-for="EventEndDateTime" class="form-control" />
                <span asp-validation-for="EventEndDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AutoClose" class="control-label"></label>
                <input asp-for="AutoClose" class="form-control" />
                <span asp-validation-for="AutoClose" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Events/Index.cshtml
@model TournamentsWebApplication.ViewModels.EventTourViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Events</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
      
       
        @Html.HiddenFor(model => model.Tournament.TournamentID)
        </div>
}


        <table class="table">
            <thead>
                <tr>
                    @*<th>
                        @Html.DisplayNameFor(model => model.FK_TournamentID)
                    </th>*@
                    <th>
                        @*@Html.DisplayNameFor(model => model.EventName)*@
                        <p>Event Name:</p>
                    </th>
                    <th>
                        @*@Html.DisplayNameFor(model => model.EventNumber)*@
                        <p>Event Number:</p>
                    </th>
                    <th>
                        @*@Html.DisplayNameFor(model => model.EventDateTime)*@
                        <p>Event Date Time:</p>
                    </th>
                    <th>
                        @*@Html.DisplayNameFor(model => model.EventEndDateTime)*@
                        <p>Event End Date Time:</p>
                    </th>
                    <th>
                        @*@Html.DisplayNameFor(model => model.AutoClose)*@
                        <p>Auto Close:</p>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Event)
                {
                    <tr>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.FK_TournamentID.TournamentID)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.EventName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EventNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EventDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EventEndDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AutoClose)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.EventID">Edit</a> |
                            <a asp-controller="EventDetails" asp-route-id="@item.EventID">Event Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.EventID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>